"""add_news_articles_table_and_agent_output_metadata

Revision ID: 2874f9e585c0
Revises: b468776d2fc2
Create Date: 2026-05-23 19:07:44.683997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2874f9e585c0'
down_revision: Union[str, None] = 'b468776d2fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_classification'), 'news_articles', ['classification'], unique=False)
    op.create_index(op.f('ix_news_articles_company_id'), 'news_articles', ['company_id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_sentiment'), 'news_articles', ['sentiment'], unique=False)
    op.add_column('agent_outputs', sa.Column('agent_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_outputs', 'agent_metadata')
    op.drop_index(op.f('ix_news_articles_sentiment'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_company_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_classification'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
