"""add registration fields

Revision ID: 4e2d730b925f
Revises: 001_initial
Create Date: 2026-05-23 14:55:37.449819
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e2d730b925f'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('companies_ticker_key'), 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.alter_column('financials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('otp_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('dob', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('risk_appetite', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('experience', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('goal', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('horizon', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('disclaimer_accepted', sa.Boolean(), nullable=False))
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.drop_column('users', 'disclaimer_accepted')
    op.drop_column('users', 'horizon')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'risk_appetite')
    op.drop_column('users', 'pan')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'city')
    op.drop_column('users', 'otp_verified')
    op.drop_column('users', 'phone')
    op.alter_column('financials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_unique_constraint(op.f('companies_ticker_key'), 'companies', ['ticker'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
