"""create_agent_outputs_table

Revision ID: b468776d2fc2
Revises: 4e2d730b925f
Create Date: 2026-05-23 17:39:38.772870
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b468776d2fc2'
down_revision: Union[str, None] = '4e2d730b925f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('concerns', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('data_completeness', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_outputs_agent_type'), 'agent_outputs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_outputs_company_id'), 'agent_outputs', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_outputs_company_id'), table_name='agent_outputs')
    op.drop_index(op.f('ix_agent_outputs_agent_type'), table_name='agent_outputs')
    op.drop_table('agent_outputs')
    # ### end Alembic commands ###
