"""add_risk_macro_models

Revision ID: eed6b6bae64d
Revises: 63734c7a018b
Create Date: 2026-05-24 15:56:22.092764
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed6b6bae64d'
down_revision: Union[str, None] = '63734c7a018b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_data_indicator'), 'macro_data', ['indicator'], unique=True)
    op.add_column('financials', sa.Column('promoter_holding_pct', sa.Numeric(), nullable=True))
    op.add_column('financials', sa.Column('promoter_pledge_pct', sa.Numeric(), nullable=True))
    op.add_column('financials', sa.Column('fii_holding_pct', sa.Numeric(), nullable=True))
    op.add_column('financials', sa.Column('dii_holding_pct', sa.Numeric(), nullable=True))
    op.add_column('financials', sa.Column('public_holding_pct', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financials', 'public_holding_pct')
    op.drop_column('financials', 'dii_holding_pct')
    op.drop_column('financials', 'fii_holding_pct')
    op.drop_column('financials', 'promoter_pledge_pct')
    op.drop_column('financials', 'promoter_holding_pct')
    op.drop_index(op.f('ix_macro_data_indicator'), table_name='macro_data')
    op.drop_table('macro_data')
    # ### end Alembic commands ###
